name: CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        path: 'ros_ws/src/knowrob' 
    #- name: Checkout rosprolog
    #  uses: actions/checkout@v2
    #  with:
    #    path: 'ros_ws/src/rosprolog'
    #    repository: knowrob/rosprolog
    # - name: Checkout iai_common_msgs
    #  uses: actions/checkout@v2
    #  with:
    #    path: 'ros_ws/src/iai_common_msgs'
    #    repository: code-iai/iai_common_msgs
    - name: Setup KnowRob workspace
      uses: betwo/github-setup-catkin@master
      env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        # Version range or exact version of ROS version to use, using SemVer's version range syntax. 
        ros-version: noetic
        # Root directory of the catkin workspace
        workspace: $GITHUB_WORKSPACE/ros_ws
    - name: Build KnowRob workspace
      shell: bash
      run: |
        sudo add-apt-repository ppa:swi-prolog/stable
        sudo apt-get update -y -qq
        sudo apt-get install swi-prolog libspdlog-dev \
            libboost-python-dev libboost-serialization-dev libboost-program-options-dev \
            libraptor2-dev librdf0-dev \
            libfmt-dev \
            doxygen graphviz
        cd ros_ws
        catkin_make_isolated
    - name: Run unit tests
      shell: bash
      run: |
        sudo systemctl start mongod
        export ROS_HOSTNAME=localhost
        roscore &
        cd $GITHUB_WORKSPACE/ros_ws/src/knowrob
        source $GITHUB_WORKSPACE/ros_ws/devel_isolated/setup.bash
        $GITHUB_WORKSPACE/ros_ws/build_isolated/knowrob/all_gtests --gtest_filter=* --gtest_output="xml:$GITHUB_WORKSPACE/gtest-knowrob.xml" --gtest_color=no || true
    - name: Report test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: "gtest-knowrob.xml"
    #####
    - name: Run doxygen
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/ros_ws/build_isolated/knowrob
        make doc
    #- name: Run pldoc
    #  if: ${{ github.event_name == 'push' }}
    #  shell: bash
    #  run: |
    #    source $GITHUB_WORKSPACE/ros_ws/devel_isolated/setup.bash
    #    cp $GITHUB_WORKSPACE/ros_ws/src/knowrob/README.md $GITHUB_WORKSPACE/ros_ws/src/knowrob/src/
    #    rosrun rosprolog rosprolog-doc knowrob
    - name: Move checkout
      run: |
        mv $GITHUB_WORKSPACE/ros_ws/src/knowrob/.git $GITHUB_WORKSPACE/
        mv $GITHUB_WORKSPACE/ros_ws/src/knowrob/* $GITHUB_WORKSPACE/
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Deploy doc to gh-pages
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@3.5.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # The branch the action should deploy to.
        BRANCH: gh-pages
        # The folder the action should deploy.
        FOLDER: doc/html
        # The folder in the target branch
        TARGET_FOLDER: ${{ steps.extract_branch.outputs.branch }}
        CLEAN: true
        SINGLE_COMMIT: true
